# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysqldb:
    type: mysql:10.2
    disk: 2048
    configuration:
        schemas:
            - mysqldb
            - texasdb
        endpoints:
            mysql:
                default_schema: mysqldb
                privileges:
                    mysqldb: admin
            texas:
                default_schema: texasdb
                privileges:
                    texasdb: admin

rediscache:
    type: redis:5.0
