smtp_on: false
smtp_host: smtp.office365.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_username: info@stronghealthycommunities.org
smtp_password: '%E@uoE0v#$Q0'
smtp_from: info@stronghealthycommunities.org
smtp_fromname: 'Strong Healthy Communities'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
